version: '3.1'
services :
  db:
    image: postgres
    container_name: ashkan
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: booking
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8083:8080