#local set up to connect with a docker postgres (now using some environment variables)
spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASS}
    properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true
#uncomment to run security
#  security:
 #   oauth2:
  #    client:
   #     registration:
    #      google:
     #       client-id: 880170717560-9nsfn8n4bpqpbmokej8dqis287p8meam.apps.googleusercontent.com
      #      client-secret: WE_KEEP_THIS_SECRET_MAYBE_WE_CAN_SAVE_SOMEWHERE_SECRET_PROPERTIES????
       #     redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
        #    scope:
         #     - email
          #    - profile

app:
  auth:
    tokenSecret: Yp3s6v9y$B&E)H@McQfThWmZq4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeS #used https://www.allkeysgenerator.com/ to create the secret key ("512-bit" long)
    tokenExpirationMsec: 900000 #15 mins
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect

