spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  mail:

    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${GMAIL_EMAIL}
    password: ${GMAIL_PASS}
    properties:
      mail:
        smtp:
          debug: true
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
          starttls.required: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
    default-encoding: UTF-8

app:
  auth:
    tokenSecret: Yp3s6v9y$B&E)H@McQfThWmZq4t7w!z%C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeS #used https://www.allkeysgenerator.com/ to create the secret key ("512-bit" long)
    tokenExpirationMsec: 900000 #15 mins
    refreshTokenExpirationMsec: 10700000 #3 hours (2.97 exactly)
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
  redirections:
    baseUri: http://localhost:3000
    loginRedirect: /login
    verificationRedirect: /verify/account/
    resetPassRedirect: /reset/pass/




